# Generated by Django 5.1.1 on 2024-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
