# Generated by Django 5.1.1 on 2024-09-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
