# Generated by Django 5.1.1 on 2024-09-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_user_post_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disaster',
        ),
        migrations.AddField(
            model_name='post',
            name='disaster_id',
            field=models.IntegerField(default=0),
        ),
    ]
